server:
  port: 9000
  
zuul: 
  prefix: /api
  routes:
    reminder-db-service:
      path: /reminder-db-service/**
      url: http://192.168.0.50:9010/    
    users-db-service:
      path: /users-db-service/**
      url: http://192.168.0.50:9011/    
    reminders-list-service:
      path: /users-db-service/**
      url: http://192.168.0.50:9012/    
    
    