spring:
  application:
    name: users-db-service
  datasource:
    url: jdbc:mysql://localhost:3306/reminderdbservice?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qazwsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 9011


logging:
  level:
    com:
      byond:
        reminderdbservice: debug
     

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    instanceInfoReplicationIntervalSeconds: 180
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
