apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: reminders
    role: registry
spec:
  type: NodePort
  #type: LoadBalancer  ## Fit for AWS or Google Services with public IPs
  ports:
    - port: 8761
      targetPort: 8761
      nodePort : 30761
      protocol: TCP
      name: registry-port
  #type: ClusterIP
  #ports:
  #- port: 8761
  #  protocol: TCP
  selector:
    app: reminders
    role: registry
