kind: PersistentVolume
apiVersion: v1
metadata:
  name: remindersdb
  labels:
    name: remindersdb
    app: reminders
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: remindersdb
    fsType: ext4
