apiVersion: v1
kind: Service
metadata:
  name: reminders-crud-service
  labels:
    app: reminders
    role: reminders-crud
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 9010
      targetPort: 9010
      protocol: TCP
      name: r-crud-port
  selector:
    app: reminders
    role: reminders-crud
