apiVersion: v1
kind: Service
metadata:
  name: users-crud-service
  labels:
    app: reminders
    role: users-crud
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 9011
      targetPort: 9011
      protocol: TCP
      name: u-crud-port
  selector:
    app: reminders
    role: users-crud
