spring:
  application:
    name: reminders-list-service
server:
  port: 9012



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    instanceInfoReplicationIntervalSeconds: 180
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
